[build]
command = "npm run build"
functions = "out_functions"
publish = "out_publish"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
package = "netlify-plugin-image-optim"

[[plugins]]
package = "netlify-plugin-minify-html"

[[plugins]]
package = "netlify-plugin-snyk"

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  buildDir = "out_publish"
  prettyURLs = true
  trailingSlash = true

[[plugins]]
package = "@netlify/plugin-lighthouse"
  [plugins.inputs.thresholds]
    performance = 0.75
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.75

[[plugins]]
package = "netlify-plugin-submit-sitemap"
  [plugins.inputs]
  baseUrl = "https://desigaar.com"
  providers = ["google", "bing", "yandex"]
  sitemapPath = "/sitemap.xml"

[[plugins]]
package = "netlify-plugin-subfont"
  [plugins.inputs]
  entryPoints = ["*.html"]
  recursive = true
  fontDisplay = "swap"
  inlineCss = false
  inlineFonts = false
  fallbacks = true

# Dutch pages
[[redirects]]
conditions = { Language = ["nl"] }
from = "/"
status = 301
to = "/nl/"

[[redirects]]
from = "/nl"
status = 301
to = "/nl/"

# English pages
[[redirects]]
from = "/"
status = 301
to = "/en/"

[[redirects]]
from = "/en"
status = 301
to = "/en/"

# 404 pages
[[redirects]]
conditions = { Language = ["nl"] }
from = "/404"
status = 301
to = "/nl/404/"

[[redirects]]
from = "/nl/*"
status = 404
to = "/nl/404/"

[[redirects]]
from = "/404"
status = 301
to = "/en/404/"

[[redirects]]
from = "/en/*"
status = 404
to = "/en/404/"

[[redirects]]
conditions = { Language = ["nl"] }
from = "/*"
status = 301
to = "/nl/404/"

[[redirects]]
from = "/*"
status = 301
to = "/en/404/"
